version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - db
    volumes:
      - ./certs:/certs
    environment:
      DISPATCH_DATABASE_SERVER: db
      DISPATCH_SECRET: ${DISPATCH_SECRET}
      DISPATCH_FCM_SECRET: ${DISPATCH_FCM_SECRET}
  db:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - dispatchdb:/data/db
volumes:
  dispatchdb: {}
